version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    networks:
      - net
    environment:
      MYSQL_DB_URL: ${MYSQL_DB_URL:-mysql://root:123456@127.0.0.1:3306/catm?charset=utf8mb4}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      FILE_STORAGE: /data
    volumes:
      - file-storage-volume:/data
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.2.0
    restart: always
    networks:
      - net
    environment:
      MYSQL_DATABASE: catm
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
  file-storage-volume:

networks:
  net:
